version: "3"

volumes:
  pprotein:
  phpmyadmin:

services:
  tun_s1:
    build: tun
    command: -N s1
    volumes:
      - /root/.ssh:/root/.ssh:ro
      - ./tun/config:/etc/ssh/ssh_config:ro
    restart: always

  tun_s2:
    build: tun
    command: -N s2
    volumes:
      - /root/.ssh:/root/.ssh:ro
      - ./tun/config:/etc/ssh/ssh_config:ro
    restart: always

  tun_s3:
    build: tun
    command: -N s3
    volumes:
      - /root/.ssh:/root/.ssh:ro
      - ./tun/config:/etc/ssh/ssh_config:ro
    restart: always

  pprotein:
    image: ghcr.io/kaz/pprotein
    volumes:
      - pprotein:/opt/pprotein/data
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    volumes:
      - phpmyadmin:/var/www/html
      - ./phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    restart: always

  nginx:
    image: nginx:alpine
    depends_on:
      - tun_s1
      - tun_s2
      - tun_s3
      - pprotein
      - phpmyadmin
    volumes:
      - phpmyadmin:/opt/phpmyadmin:ro
      - ./nginx/tls:/etc/nginx/tls:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    restart: always
