version: "3"

volumes:
  pprotein:
  phpmyadmin:

services:
  tun_s1:
    build: tun
    command: -N s1
    volumes:
      - ./tun/config:/root/.ssh/config:ro
      - /root/.gnupg/S.gpg-agent.ssh:/root/.gnupg/S.gpg-agent.ssh
    environment:
      SSH_AUTH_SOCK: /root/.gnupg/S.gpg-agent.ssh
    restart: always

  tun_s2:
    build: tun
    command: -N s2
    volumes:
      - ./tun/config:/root/.ssh/config:ro
      - /root/.gnupg/S.gpg-agent.ssh:/root/.gnupg/S.gpg-agent.ssh
    environment:
      SSH_AUTH_SOCK: /root/.gnupg/S.gpg-agent.ssh
    restart: always

  tun_s3:
    build: tun
    command: -N s3
    volumes:
      - ./tun/config:/root/.ssh/config:ro
      - /root/.gnupg/S.gpg-agent.ssh:/root/.gnupg/S.gpg-agent.ssh
    environment:
      SSH_AUTH_SOCK: /root/.gnupg/S.gpg-agent.ssh
    restart: always

  pprotein:
    build: pprotein
    volumes:
      - pprotein:/opt/pprotein/data
      - ./pprotein/kataribe.toml:/opt/pprotein/kataribe.toml:ro
    environment:
      SSH_AUTH_SOCK: /root/.gnupg/S.gpg-agent.ssh
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    volumes:
      - phpmyadmin:/var/www/html
      - ./phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    restart: always

  nginx:
    image: nginx:alpine
    depends_on:
      - tun_s1
      - tun_s2
      - tun_s3
      - pprotein
      - phpmyadmin
    volumes:
      - phpmyadmin:/opt/phpmyadmin:ro
      - ./nginx/tls:/etc/nginx/tls:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    restart: always
