- name: download alp
  get_url:
    url: https://github.com/tkuchiki/alp/releases/download/v1.0.8/alp_linux_amd64.zip
    checksum: md5:6b83ded5f4131ad67e762203f29ca33b
    dest: /tmp/alp.zip
  register: alp

- name: install alp
  unarchive:
    remote_src: yes
    src: /tmp/alp.zip
    dest: /usr/local/bin
  when: alp.changed
