- name: set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: install tools
  apt:
    update_cache: yes
    pkg:
      - dstat
      - fish
      - graphviz
      - nano
      - unzip
      - percona-toolkit
      - redis

- name: put /etc/sysctl.d/isucon.conf
  copy:
    src: isucon.conf
    dest: /etc/sysctl.d/isucon.conf
    mode: 0644
  register: sysctl

- name: sysctl -p /etc/sysctl.d/isucon.conf
  command: sysctl -p /etc/sysctl.d/isucon.conf
  when: sysctl.changed

- name: create service.d
  file:
    state: directory
    path: /etc/systemd/system/{{ item }}.service.d
  loop:
    - nginx
    - mysql
    - web-golang

- name: override systemd services
  copy:
    src: override.conf
    dest: /etc/systemd/system/{{ item }}.service.d/override.conf
    mode: 0644
  loop:
    - nginx
    - mysql
    - web-golang

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: create directories
  file:
    state: directory
    path: "{{ item }}"
    mode: 0777
  loop:
    - /var/log/nginx
    - /var/log/mysql

- name: touch files
  file:
    state: touch
    path: "{{ item }}"
    mode: 0666
  loop:
    - /var/log/nginx/access.log
    - /var/log/mysql/mysql-slow.log
