- name: set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: install packages
  apt:
    update_cache: yes
    name:
      - docker
      - docker-compose
      - fish
      - git
      - nano
      - rsync

- name: enable docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: create ssh dir
  file:
    path: /root/.ssh
    state: directory
    mode: 0700

- name: put id_ecdsa
  copy:
    src: ../../keys/files/id_ecdsa
    dest: /root/.ssh/id_ecdsa
    mode: 0600

- name: synchronize docker-copmose configurations
  synchronize:
    src: "{{ playbook_dir }}/../hq"
    dest: /opt

- name: start containers
  command: docker-compose up -d
  args:
    chdir: /opt/hq
