- name: create ssh dir for root
  file:
    path: /root/.ssh
    state: directory
    mode: 0700

- name: put id_rsa for root
  copy:
    src: ../hq/tun/id_rsa
    dest: /root/.ssh/id_rsa
    mode: 0600

- name: put .gitconfig for root
  copy:
    src: .gitconfig
    dest: /root/.gitconfig
    mode: 0644

- name: create ssh dir for isucon
  file:
    path: /home/isucon/.ssh
    state: directory
    mode: 0700
    owner: isucon
    group: isucon

- name: put id_rsa for isucon
  copy:
    src: ../hq/tun/id_rsa
    dest: /home/isucon/.ssh/id_rsa
    mode: 0600
    owner: isucon
    group: isucon

- name: put .gitconfig for isucon
  copy:
    src: .gitconfig
    dest: /home/isucon/.gitconfig
    mode: 0644
    owner: isucon
    group: isucon

- name: clone repository
  become_user: isucon
  git:
    repo: git@github.com:narusejun/isucon11-exercise.git
    dest: /home/isucon/isucon11-exercise
    accept_hostkey: yes
