- name: download slackcat
  get_url:
    url: https://github.com/bcicen/slackcat/releases/download/1.7.3/slackcat-1.7.3-linux-amd64
    checksum: sha256:df9d1c3d16090e64e96ad268a75c757ecf0a22f58c8ae3c98e284af486a5d1ba
    dest: /usr/local/bin/slackcat.original
    mode: "6755"

- name: put script
  copy:
    src: slackcat.sh
    dest: /usr/local/bin/slackcat
    mode: 0755

- name: create config dir
  file:
    path: /root/.config/slackcat
    state: directory
    recurse: yes

- name: put configuration
  copy:
    src: config
    dest: /root/.config/slackcat/config
    mode: 0644
